task_manager/labels/urls.py
from django.urls import path

from .views import (
    CreateLabelsView,
    DeleteLabelsView,
    IndexLabelsView,
    UpdateLabelsView,
)

app_name = "labels"

urlpatterns = [
    path("", IndexLabelsView.as_view(), name="index"),
    path("create/", CreateLabelsView.as_view(), name="create"),
    path("<int:pk>/update/", UpdateLabelsView.as_view(), name="update"),
    path("<int:pk>/delete/", DeleteLabelsView.as_view(), name="delete"),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks.views import (
    CreateTaskView,
    DeleteTaskView,
    IndexTaskView,
    ShowTaskView,
    UpdateTaskView,
)

app_name = "tasks"

urlpatterns = [
    path("", IndexTaskView.as_view(), name="index"),
    path("create/", CreateTaskView.as_view(), name="create"),
    path("<int:pk>/update/", UpdateTaskView.as_view(), name="update"),
    path("<int:pk>/delete/", DeleteTaskView.as_view(), name="delete"),
    path("<int:pk>/", ShowTaskView.as_view(), name="show"),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager.views import CustomLoginView, CustomLogoutView, IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("users/", include("task_manager.users.urls")),
    path("statuses/", include("task_manager.statuses.urls")),
    path("tasks/", include("task_manager.tasks.urls")),
    path("labels/", include("task_manager.labels.urls")),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users.views import (
    CreateUserView,
    DeleteUserView,
    IndexUserView,
    UpdateUserView,
)

app_name = "users"

urlpatterns = [
    path("", IndexUserView.as_view(), name="index"),
    path("create/", CreateUserView.as_view(), name="create"),
    path("<int:pk>/update/", UpdateUserView.as_view(), name="update"),
    path("<int:pk>/delete/", DeleteUserView.as_view(), name="delete"),
]

task_manager/labels/models.py
from django.db import models


# Create your models here.
class Label(models.Model):
    name = models.CharField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models


# Create your models here.
class Status(models.Model):
    name = models.CharField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import User


# Create your models here.
class Task(models.Model):
    name = models.CharField(unique=True)
    description = models.TextField(null=True, blank=True)
    status = models.ForeignKey(
        Status, on_delete=models.CASCADE, related_name="status", null=True
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author", null=True
    )
    executor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="executor", null=True
    )
    labels = models.ManyToManyField(Label, related_name="labels", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    def __str__(self):
        full_name = self.first_name + " " + self.last_name
        return full_name

task_manager/labels/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ["name"]
        labels = {"name": _("Name")}

    def clean_name(self):
        label_name = self.cleaned_data["name"]
        label = Label.objects.filter(name=label_name)

        if label.exists() and self.instance.pk != label[0].pk:
            raise forms.ValidationError(
                _("Task status with this Name already exists.")
            )
        return self.cleaned_data["name"]

task_manager/statuses/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from task_manager.statuses.models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = [
            "name",
        ]
        labels = {
            "name": _("Name"),
        }

    def clean_name(self):
        status_name = self.cleaned_data["name"]
        stasus = Status.objects.filter(name=status_name)

        if stasus.exists() and self.instance.pk != stasus[0].pk:
            raise forms.ValidationError(
                _("Task status with this Name already exists.")
            )
        return self.cleaned_data["name"]

task_manager/tasks/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label
from task_manager.tasks.models import Task


class SearchTaskForm(forms.ModelForm):
    self_tasks = forms.BooleanField(
        label=_("Only my tasks"),
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )
    label = forms.ModelChoiceField(
        queryset=Label.objects.all(),
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
        label=_("Label"),
        empty_label="---------",
    )

    class Meta:
        model = Task
        fields = [
            "status",
            "executor",
            "label",
            "self_tasks",
        ]
        labels = {
            "status": _("Status"),
            "executor": _("Executor"),
        }
        widgets = {
            "status": forms.Select(attrs={"class": "form-control"}),
            "executor": forms.Select(attrs={"class": "form-control"}),
        }
        empty_label = {
            "status": "---------",
            "executor": "---------",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["status"].required = False
        self.fields["executor"].required = False


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "status",
            "executor",
            "labels",
        ]
        labels = {
            "name": _("Name"),
            "description": _("Description"),
            "status": _("Status"),
            "executor": _("Executor"),
            "labels": _("Labels"),
        }
        widgets = {
            "status": forms.Select(attrs={"class": "form-control"}),
            "labels": forms.SelectMultiple(attrs={"class": "form-control"}),
        }
        empty_label = {
            "status": "---------",
            "executor": "---------",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["executor"].required = False

task_manager/labels/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    UpdateView,
)

from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label
from task_manager.mixins import LoginMixin
from task_manager.tasks.models import Task


class IndexLabelsView(LoginMixin, View):
    def get(self, request):
        labels = Label.objects.all()
        return render(request, "labels/index.html", context={"labels": labels})


class CreateLabelsView(LoginMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = "labels/create.html"
    success_url = reverse_lazy("labels:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("The label was successfully created."))
        return response


class UpdateLabelsView(LoginMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = "labels/update.html"
    success_url = reverse_lazy("labels:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Label successfully updated"))
        return response


class DeleteLabelsView(LoginMixin, DeleteView):
    model = Label
    template_name = "labels/delete.html"
    success_url = reverse_lazy("labels:index")

    def form_valid(self, form):
        if Task.objects.filter(labels=self.object).exists():
            messages.error(
                self.request, _("Cannot delete label because it is in use")
            )
            return redirect("labels:index")
        response = super().form_valid(form)
        messages.success(self.request, _("Label successfully deleted"))
        return response

task_manager/statuses/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    UpdateView,
)

from task_manager.mixins import LoginMixin
from task_manager.tasks.models import Task

from .forms import StatusForm
from .models import Status


class IndexStatusesView(LoginMixin, View):
    def get(self, request):
        statuses = Status.objects.all().order_by("id")
        return render(
            request, "statuses/index.html", context={"statuses": statuses}
        )


class CreateStatusesView(LoginMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = "statuses/create.html"
    success_url = reverse_lazy("statuses:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Status successfully created"))
        return response


class UpdateStatusesView(LoginMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = "statuses/update.html"
    success_url = reverse_lazy("statuses:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Status successfully updated"))
        return response


class DeleteStatusesView(LoginMixin, DeleteView):
    model = Status
    template_name = "statuses/delete.html"
    success_url = reverse_lazy("statuses:index")

    def form_valid(self, form):
        if Task.objects.filter(status=self.object).exists():
            messages.error(
                self.request, _("Cannot delete status because it is in use")
            )
            return redirect("statuses:index")
        response = super().form_valid(form)
        messages.success(self.request, _("Status successfully deleted"))
        return response

task_manager/tasks/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    UpdateView,
)

from task_manager.mixins import LoginMixin, TaskMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task


class IndexTaskView(LoginMixin, View):
    def get(self, request):
        tasks = Task.objects.all()
        filterset = TaskFilter(request.GET, queryset=tasks, request=request)
        return render(
            request,
            "tasks/index.html",
            context={
                "form": filterset.form,
                "tasks": filterset.qs,
            },
        )


class CreateTaskView(LoginMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/create.html"
    success_url = reverse_lazy("tasks:index")

    def form_valid(self, form):
        task = form.save(commit=False)
        task.author = self.request.user
        task.save()
        response = super().form_valid(form)
        messages.success(self.request, _("Task successfully created"))
        return response


class UpdateTaskView(LoginMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/update.html"
    success_url = reverse_lazy("tasks:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Task successfully updated"))
        return response


class DeleteTaskView(TaskMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy("tasks:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Task successfully deleted"))
        return response


class ShowTaskView(LoginMixin, View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        return render(request, "tasks/show.html", context={"task": task})

task_manager/users/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    UpdateView,
)

from task_manager.mixins import UserMixin
from task_manager.tasks.models import Task
from task_manager.users.forms import UserForm
from task_manager.users.models import User


class IndexUserView(View):
    def get(self, request):
        # raise Exception("ROLLBAR TEST! Delete later!") DELETE!
        users = User.objects.all().order_by("id")
        return render(
            request,
            "users/index.html",
            context={"users": users},
        )


class CreateUserView(CreateView):
    model = User
    form_class = UserForm
    template_name = "users/create.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data["password1"])
        user.save()

        messages.success(self.request, _("User registered successfully"))

        return super().form_valid(form)


class UpdateUserView(UserMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = "users/update.html"
    success_url = reverse_lazy("users:index")

    def form_valid(self, form):
        if "password1" in form.cleaned_data and form.cleaned_data["password1"]:
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password1"])
            user.save()
        else:
            form.save()

        messages.success(self.request, _("User successfully changed."))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _("Please correct the errors below."))
        return super().form_invalid(form)


class DeleteUserView(UserMixin, DeleteView):
    model = User
    template_name = "users/delete.html"
    success_url = reverse_lazy("users:index")

    def form_valid(self, form):
        if Task.objects.filter(executor=self.object).exists():
            messages.error(
                self.request, _("Cannot delete user because it is in use")
            )
            return redirect("users:index")
        respose = super().form_valid(form)
        messages.success(self.request, _("User successfully deleted"))
        return respose

task_manager/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View


class IndexView(View):
    def get(self, request):
        return render(request, "index.html", context={})


class CustomLoginView(LoginView):
    template_name = "login.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("You are login"))
        return response

    def get_success_url(self):
        return reverse_lazy("index")


class CustomLogoutView(View):
    def get(self, request):
        return redirect("index")

    def post(self, request):
        if request.user.is_authenticated:
            logout(request)
            messages.info(request, _("You are logout"))
        else:
            messages.warning(request, _("You are not logged in"))

        return redirect("index")

task_manager/templates/tasks/create.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
<main>
  <div class="container-md mt-3">
    <h1>{% translate "Create task" %}</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content=_('Create') %}
    </form>
</main>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<main>
  <div class="container">
    <div class="row justify-content-center mt-3">
        <h1 class="display-5">{% translate 'Deleting task' %}</h1>
        <p class="lead">{% translate 'Are you sure you want to delete' %} {{ task.name }}?</p>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_button content=_("Yes, delete") button_type="submit" button_class="btn-danger" element="input" %}
        </form>
    </div>
  </div>
</main>
{% endblock %}

task_manager/templates/tasks/index.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load django_bootstrap5 %}
<main>
  <div class="container-md mt-3">
    <h1>{% translate "Tasks" %}</h1>
    <a href="{% url 'tasks:create' %}" class="btn btn-primary">{% translate "Create task" %}</a>
    <div class="container-md bg-body-tertiary mt-3 mb-3 border rounded-3">
        <div class="p-3">
            <form action="{% url 'tasks:index' %}" method="get">
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content=_('Show') %}
            </form>
        </div>
    </div>
    <table class="table table-striped mt-2" data-test="checks">
        <thead>
            <tr>
              <th>ID</th>
              <th>{% translate "Name" %}</th>
              <th>{% translate "Status" %}</th>
              <th>{% translate "Autor" %}</th>
              <th>{% translate "Executor" %}</th>
              <th>{% translate "Create date" %}</th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            {% if tasks %}
            {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td><a href="{% url 'tasks:show' task.id %}">{{ task.name }}</a></td>
                <td>{{ task.status }}</td>
                <td>{{ task.author }}</td>
                <td>{{ task.executor|default_if_none:"" }}</td>
                <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
                <td>
                    <a href="{% url 'tasks:update' task.id %}">{% translate "Edit" %}</a><br>
                    <a href="{% url 'tasks:delete' task.id %}">{% translate "Delete" %}</a>
                </td>
            </tr>
            {% endfor %}
            {% endif %}
        </tbody>
    </table>
  </div>
</main>
{% endblock %}

task_manager/templates/tasks/show.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
<main>
  <div class="container-md mt-3">
    <h1>{% translate "View task" %}</h1>
    <div class="container bg-secondary text-white border rounded-3 rounded-bottom-0 py-2 px-3">
        <h2>{{ task.name }}</h2>
    </div>
    <div class="container bg-light border rounded-3 rounded-top-0 p-3">
        <p>{{ task.description }}</p>
        <hr>
        <div class="container ">
        <div class="row p-1">
            <div class="col">{% translate "Author" %}</div>
            <div class="col">{{ task.author }}</div>
        </div>
        <div class="row p-1">
            <div class="col">{% translate "Executor" %}</div>
            <div class="col">{{ task.executor }}</div>
        </div>
        <div class="row p-1">
            <div class="col">{% translate "Status" %}</div>
            <div class="col">{{ task.status }}</div>
        </div>
        <div class="row p-1">
            <div class="col">{% translate "Date of creation" %}</div>
            <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
        </div>
        <div class="row p-1">
            <div class="col">
            <h6>{% translate "Labels" %}:</h6>
            <ul>
                {% for label in task.labels.all %}
                    <li>{{ label.name }}</li>
                {% endfor %}
            </ul>
            </div>
        </div>
        <div class="row p-1">
            <div class="col">
            <a href="{% url 'tasks:update' task.id %}">{% translate "Edit" %}</a><br>
            <a href="{% url 'tasks:delete' task.id %}">{% translate "Delete" %}</a>
            </div>
        </div>
        </div>
    </div>
</main>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
<main>
  <div class="container-md mt-3">
    <h1>{% translate "Changing a task" %}</h1>
    <form action="{% url 'tasks:update' task.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content=_('Change') %}
    </form>
</main>
{% endblock %}